project_id = "tiprwyccuzftpjyvnink"

[functions.get-signed-url]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-video]
verify_jwt = true
